#Can add other stages for linting and testing
FROM node:alpine AS builder

WORKDIR /app
COPY ./srcs/package*.json ./
RUN npm install
# RUN NODE_ENV=development npm i
COPY ./srcs .
RUN npm run build

#Prod
FROM node:alpine

WORKDIR /app
COPY ./srcs/package*.json ./
RUN npm install --only=production
COPY --from=builder /app/dist ./
EXPOSE 5555/udp
EXPOSE 5555/tcp
ENTRYPOINT ["node","./final.js"]